### ISSUE TITLE
Incompatible with 1.12 (Even though it's supposed to be updated)

### ISSUE THREAD

**Issue by ghost** [Lemonszz/SimpleTeleporters#9]
Title is self explanatory.
For more info about it, refer to this thread on the forge forums: http://www.minecraftforge.net/forum/topic/59216-112-hates-mods-crash-even-with-compatible-mods/

I crash when running Simple Teleporters in 1.12, even though it's supposed to be updated.
This happens with other mods to, Such as Quark, RFtools and Iron chests, so I would greatly appreciate it if anyone reading this could try and get the word out about this so authors can update.
Regards,
-L0ST

**Comment by Endmateria** [comment]
@L0ST5ILVER His mod is updated to 1.12, but it's built against Forge version 1.12-14.21.1.2387 (https://github.com/Lemonszz/SimpleTeleporters/commit/a24a8e69e36b6248dc71ed6f5a77c8a3a83642cc).  Just because a mod is compatible with 1.12, doesn't mean that it's compatible with "ALL" Forge versions for 1.12.  When Forge changes something big, mods fall out of sync and need to be updated.

**Comment by Lemonszz** [comment]
Double check you have the latest version
https://minecraft.curseforge.com/projects/simple-teleporters/files/2443075 <- that is the latest version.

Although, there is currently a bug with crafting the ender shard, it should still load fine.

Also make sure that you are downloading mods from the correct source (Curseforge) as I'm fairly sure those other mods are also updated.

Oh, and make sure you have the latest forge

**Comment by Lemonszz** [comment]
The latest version is now here https://minecraft.curseforge.com/projects/simple-teleporters/files/2446988
